version: "3.3"
volumes:
  storage: {}
  db: {}
  contracts: {}
services:
  casper-node:
    build: ./build
    ports:
        - "7777:7777"
        - "34553:34553"
        - "34552:34552"
    volumes: 
        - "./etc/casper/config.toml:/etc/casper/config.toml"
        - "./etc/casper/validator_keys:/etc/casper/validator_keys"
        - "storage:/root/.local/share/casper-node"
        - "db:/var/lib/casper/casper-node"
        - "contracts:/contracts"
    command: validator /etc/casper/config.toml
    restart: unless-stopped
  
  build-env:
    image: rust:latest
    volumes:
        - "contracts:/build"